version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    links:
      - mongodb

  mongodb:
    image: mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
