pipeline {
    agent {
        docker {
            image 'node:8.11.1-alpine'
            args '-p 3000:3000 --env NODE_ENV=development --env DATABASE=mongodb://mongodb:27017/playground --env PORT=3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh "/usr/bin/docker-compose -f docker-compose.yml up -d --build"
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
